project:
  type: website

website:
  title: "X-CITE"
  navbar:
    left:
      - href: index.md
        text: Home
      - about.md

format:
  html:
    css: styles.css
    toc: true

theme:
  light: simplex
  dark: [simplex, theme-dark.scss]

# https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto
