project:
  type: website

website:
  title: "X-CITE"
  navbar:
    left:
      - href: index.md
        text: Home
      - about.md
  page-footer:
    border: true
    left:
      - icon: github
        href: https://github.com/RENCI-NRIG/X-CITE

  repo-url: https://github.com/RENCI-NRIG/X-CITE
  repo-actions: [edit, issue]

  reader-mode: true

format:
  html:
    css: styles.css
    toc: true

theme:
  light: simplex
  dark: [simplex, theme-dark.scss]

# https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto
