project:
  type: website

website:
  title: "X-CITE"
  navbar:
    left:
      - href: index.md
        text: Home
      - about.md

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

# https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto
