project:
  type: website

website:
  title: "X-CITE"
  favicon: /images/logo.png

  navbar:
    left:
      - href: index.md
        text: Home
      - about.md
  page-footer:
    border: true
    center: |-
      X-CITE is supported by the NSF under award numbers
      [OAC-2320373](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2320373),
      [OAC-2320374](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2320374),
      and
      [OAC-2320375](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2320375).

      Contact [anirban@renci.org](mailto:anirban@renci.org) for more
      information.

  repo-url: https://github.com/RENCI-NRIG/X-CITE
  repo-actions: [edit, issue]

  reader-mode: true

format:
  html:
    css: styles.css
    toc: true
  revealjs:
    theme: default
  beamer:
    theme: default

theme:
  light: simplex
  dark: [simplex, theme-dark.scss]

# https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto
