# Workflow for rendering and deploying quarto site to Netlify and
# quarto.pub.
#
# Via https://quarto.org/docs/publishing/github-pages.html

name: Publish

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    # permissions for gh-pages
    permissions:
      contents: write
      pages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Publish on Netlify (https://xcitecourse.org/ and
      # x-cite-course.netlify.app).
      - name: Render and Publish on netlify
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      # Publish on Quarto.pub (https://x-cite.quarto.pub/).
      - name: Render and Publish on quarto.pub
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: quarto-pub
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
