# Workflow for rendering and deploying quarto site to Netlify and
# quarto.pub.
#
# Via https://quarto.org/docs/publishing/github-pages.html

name: Publish

on:
  workflow_dispatch:
  push:
    branches: main

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

  permissions:
    contents: write
    pages: write

  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      # env:
      #   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # with:
      #   tinytex: true

    - name: Print Quarto version
      run: quarto --version

    - name: Print Quarto tools
      run: quarto tools

    # Publish on GitHub Pages
    - name: Render and publish on GitHub Pages
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # # Publish on Netlify (x-cite-course.netlify.app).
    # - name: Render and Publish on netlify
    #   uses: quarto-dev/quarto-actions/publish@v2
    #   with:
    #     target: netlify
    #     # NETLIFY_AUTH_TOKEN is a personal access token generated at
    #     # https://app.netlify.com/user/applications, and it expires
    #     # after an interval.
    #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

    # Publish on Quarto.pub (https://x-cite.quarto.pub/).
    - name: Render and Publish on quarto.pub
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: quarto-pub
        # QUARTO_PUB_AUTH_TOKEN is generated at
        # https://quartopub.com/profile.
        QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
