# Run `quarto render` on pull requests.

name: Render

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # env:
        #   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   tinytex: true

      # - name: Set up TeXLive
      #   uses: teatimeguest/setup-texlive-action@v3

      # - name: Check `tlmgr` version
      #   run: tlmgr --version

      - name: Check quarto version
        run: quarto --version

      - name: Print Quarto tools
        run: quarto tools

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
